#include <sys/stat.h>
#include <sys/types.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "absolutePath.c"
#include "fullSize.c"
#include "nameext.c"
#include "split.c"
#include "merge.c"